name: 'Set Variables'
description: 'Set app version suffix'
inputs:
  os:
    description: 'OS designator'
    required: true
outputs:
  suffix:
    description: 'Suffix for the compiled version'
    value: ${{ steps.main.outputs.suffix }}

  config:
    description: 'Config to use (Win only)'
    value: ${{ steps.main.outputs.config }}

  dep:
    description: 'Dependency file suffix'
    value: ${{ steps.main.outputs.dep }}

runs:
  using: "composite"
  steps: 
    - id: main
      run: |
        if [[ $GITHUB_REF == *"refs/tags/"* ]]
        then
          echo "Found Tag : ${GITHUB_REF#refs/tags/}"
          echo "::set-output name=suffix::${{ inputs.os }}-${GITHUB_REF#refs/tags/}"
          echo "::set-output name=config::Release"
          echo "::set-output name=dep::release"
        else
          echo "::set-output name=suffix::${{ inputs.os }}-bleedingedge"
          echo "::set-output name=config::Debug"
          echo "::set-output name=dep::debug"
        fi
      shell: bash
